# Generated by Django 6.1 on 2026-08-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(max_length=40)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('hour_of_day', models.IntegerField()),
                ('rainfall_mm', models.FloatField()),
                ('avg_congestion_percent', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
